export const SET_AUTHENTECATED_USER = "SET_AUTHENTECATED_USER";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const REMOVE_ANSWER = "REMOVE_ANSWER";
export const GET_USERS = "GET_USERS";
